export const BASIC_BOOK_ID = 'basic_english'

export const basicEnglishWords = [
  {
    id: 'word_basic_001',
    word: 'ability',
    phonetic: '/əˈbɪləti/',
    partOfSpeech: 'n.',
    meaningZh: '能力；才能',
    exampleEn: 'She has the ability to solve difficult problems.',
    exampleZh: '她有解决难题的能力。',
    tags: 'basic,school',
    difficulty: 2,
  },
  {
    id: 'word_basic_002',
    word: 'accept',
    phonetic: '/əkˈsept/',
    partOfSpeech: 'v.',
    meaningZh: '接受；同意',
    exampleEn: 'He accepted the invitation gladly.',
    exampleZh: '他高兴地接受了邀请。',
    tags: 'basic,verb',
    difficulty: 2,
  },
  {
    id: 'word_basic_003',
    word: 'achieve',
    phonetic: '/əˈtʃiːv/',
    partOfSpeech: 'v.',
    meaningZh: '实现；达到',
    exampleEn: 'You can achieve your goal with practice.',
    exampleZh: '通过练习你可以实现目标。',
    tags: 'basic,verb',
    difficulty: 3,
  },
  {
    id: 'word_basic_004',
    word: 'active',
    phonetic: '/ˈæktɪv/',
    partOfSpeech: 'adj.',
    meaningZh: '积极的；活跃的',
    exampleEn: 'He is active in class discussions.',
    exampleZh: '他在课堂讨论中很积极。',
    tags: 'basic,adjective',
    difficulty: 1,
  },
  {
    id: 'word_basic_005',
    word: 'address',
    phonetic: '/əˈdres/',
    partOfSpeech: 'n./v.',
    meaningZh: '地址；处理',
    exampleEn: 'Please write your address clearly.',
    exampleZh: '请清楚地写下你的地址。',
    tags: 'basic,noun',
    difficulty: 2,
  },
  {
    id: 'word_basic_006',
    word: 'advice',
    phonetic: '/ədˈvaɪs/',
    partOfSpeech: 'n.',
    meaningZh: '建议；忠告',
    exampleEn: 'My teacher gave me useful advice.',
    exampleZh: '我的老师给了我有用的建议。',
    tags: 'basic,noun',
    difficulty: 2,
  },
  {
    id: 'word_basic_007',
    word: 'affect',
    phonetic: '/əˈfekt/',
    partOfSpeech: 'v.',
    meaningZh: '影响',
    exampleEn: 'Sleep can affect your memory.',
    exampleZh: '睡眠会影响你的记忆力。',
    tags: 'basic,verb',
    difficulty: 3,
  },
  {
    id: 'word_basic_008',
    word: 'allow',
    phonetic: '/əˈlaʊ/',
    partOfSpeech: 'v.',
    meaningZh: '允许；准许',
    exampleEn: 'The library does not allow loud talking.',
    exampleZh: '图书馆不允许大声说话。',
    tags: 'basic,verb',
    difficulty: 2,
  },
  {
    id: 'word_basic_009',
    word: 'ancient',
    phonetic: '/ˈeɪnʃənt/',
    partOfSpeech: 'adj.',
    meaningZh: '古代的；古老的',
    exampleEn: 'We visited an ancient city.',
    exampleZh: '我们参观了一座古城。',
    tags: 'basic,history',
    difficulty: 2,
  },
  {
    id: 'word_basic_010',
    word: 'appear',
    phonetic: '/əˈpɪə/',
    partOfSpeech: 'v.',
    meaningZh: '出现；显得',
    exampleEn: 'Stars appear in the night sky.',
    exampleZh: '星星出现在夜空中。',
    tags: 'basic,verb',
    difficulty: 2,
  },
  {
    id: 'word_basic_011',
    word: 'arrive',
    phonetic: '/əˈraɪv/',
    partOfSpeech: 'v.',
    meaningZh: '到达',
    exampleEn: 'The train will arrive at nine.',
    exampleZh: '火车将在九点到达。',
    tags: 'basic,travel',
    difficulty: 1,
  },
  {
    id: 'word_basic_012',
    word: 'attention',
    phonetic: '/əˈtenʃn/',
    partOfSpeech: 'n.',
    meaningZh: '注意；关注',
    exampleEn: 'Please pay attention to the question.',
    exampleZh: '请注意这个问题。',
    tags: 'basic,noun',
    difficulty: 2,
  },
  {
    id: 'word_basic_013',
    word: 'available',
    phonetic: '/əˈveɪləbl/',
    partOfSpeech: 'adj.',
    meaningZh: '可获得的；有空的',
    exampleEn: 'This book is available in the library.',
    exampleZh: '这本书在图书馆可以借到。',
    tags: 'basic,adjective',
    difficulty: 3,
  },
  {
    id: 'word_basic_014',
    word: 'balance',
    phonetic: '/ˈbæləns/',
    partOfSpeech: 'n./v.',
    meaningZh: '平衡；使平衡',
    exampleEn: 'A good life needs balance.',
    exampleZh: '良好的生活需要平衡。',
    tags: 'basic,noun',
    difficulty: 2,
  },
  {
    id: 'word_basic_015',
    word: 'benefit',
    phonetic: '/ˈbenɪfɪt/',
    partOfSpeech: 'n./v.',
    meaningZh: '益处；受益',
    exampleEn: 'Exercise has many benefits.',
    exampleZh: '锻炼有很多益处。',
    tags: 'basic,health',
    difficulty: 2,
  },
  {
    id: 'word_basic_016',
    word: 'borrow',
    phonetic: '/ˈbɒrəʊ/',
    partOfSpeech: 'v.',
    meaningZh: '借入',
    exampleEn: 'Can I borrow your dictionary?',
    exampleZh: '我能借你的词典吗？',
    tags: 'basic,school',
    difficulty: 1,
  },
  {
    id: 'word_basic_017',
    word: 'brief',
    phonetic: '/briːf/',
    partOfSpeech: 'adj.',
    meaningZh: '简短的；短暂的',
    exampleEn: 'The teacher gave a brief introduction.',
    exampleZh: '老师做了简短介绍。',
    tags: 'basic,adjective',
    difficulty: 2,
  },
  {
    id: 'word_basic_018',
    word: 'calm',
    phonetic: '/kɑːm/',
    partOfSpeech: 'adj./v.',
    meaningZh: '冷静的；使平静',
    exampleEn: 'Stay calm before the exam.',
    exampleZh: '考试前保持冷静。',
    tags: 'basic,feeling',
    difficulty: 1,
  },
  {
    id: 'word_basic_019',
    word: 'challenge',
    phonetic: '/ˈtʃælɪndʒ/',
    partOfSpeech: 'n./v.',
    meaningZh: '挑战',
    exampleEn: 'Learning a new language is a challenge.',
    exampleZh: '学习一门新语言是一个挑战。',
    tags: 'basic,study',
    difficulty: 2,
  },
  {
    id: 'word_basic_020',
    word: 'choice',
    phonetic: '/tʃɔɪs/',
    partOfSpeech: 'n.',
    meaningZh: '选择',
    exampleEn: 'You made a good choice.',
    exampleZh: '你做出了一个好选择。',
    tags: 'basic,noun',
    difficulty: 1,
  },
  {
    id: 'word_basic_021',
    word: 'common',
    phonetic: '/ˈkɒmən/',
    partOfSpeech: 'adj.',
    meaningZh: '普通的；常见的',
    exampleEn: 'This is a common mistake.',
    exampleZh: '这是一个常见错误。',
    tags: 'basic,adjective',
    difficulty: 1,
  },
  {
    id: 'word_basic_022',
    word: 'compare',
    phonetic: '/kəmˈpeə/',
    partOfSpeech: 'v.',
    meaningZh: '比较',
    exampleEn: 'Compare the two answers carefully.',
    exampleZh: '仔细比较这两个答案。',
    tags: 'basic,verb',
    difficulty: 2,
  },
  {
    id: 'word_basic_023',
    word: 'complete',
    phonetic: '/kəmˈpliːt/',
    partOfSpeech: 'v./adj.',
    meaningZh: '完成；完整的',
    exampleEn: 'Please complete the form.',
    exampleZh: '请填写完整这张表格。',
    tags: 'basic,verb',
    difficulty: 2,
  },
  {
    id: 'word_basic_024',
    word: 'condition',
    phonetic: '/kənˈdɪʃn/',
    partOfSpeech: 'n.',
    meaningZh: '条件；状况',
    exampleEn: 'The road is in good condition.',
    exampleZh: '这条路状况良好。',
    tags: 'basic,noun',
    difficulty: 3,
  },
  {
    id: 'word_basic_025',
    word: 'connect',
    phonetic: '/kəˈnekt/',
    partOfSpeech: 'v.',
    meaningZh: '连接；联系',
    exampleEn: 'The bridge connects the two towns.',
    exampleZh: '这座桥连接了两个城镇。',
    tags: 'basic,verb',
    difficulty: 2,
  },
  {
    id: 'word_basic_026',
    word: 'consider',
    phonetic: '/kənˈsɪdə/',
    partOfSpeech: 'v.',
    meaningZh: '考虑；认为',
    exampleEn: 'You should consider his advice.',
    exampleZh: '你应该考虑他的建议。',
    tags: 'basic,verb',
    difficulty: 3,
  },
  {
    id: 'word_basic_027',
    word: 'continue',
    phonetic: '/kənˈtɪnjuː/',
    partOfSpeech: 'v.',
    meaningZh: '继续',
    exampleEn: 'We will continue the lesson tomorrow.',
    exampleZh: '我们明天继续上课。',
    tags: 'basic,verb',
    difficulty: 2,
  },
  {
    id: 'word_basic_028',
    word: 'create',
    phonetic: '/kriˈeɪt/',
    partOfSpeech: 'v.',
    meaningZh: '创造；创建',
    exampleEn: 'Students can create their own projects.',
    exampleZh: '学生可以创建自己的项目。',
    tags: 'basic,verb',
    difficulty: 2,
  },
  {
    id: 'word_basic_029',
    word: 'culture',
    phonetic: '/ˈkʌltʃə/',
    partOfSpeech: 'n.',
    meaningZh: '文化',
    exampleEn: 'Food is part of culture.',
    exampleZh: '食物是文化的一部分。',
    tags: 'basic,society',
    difficulty: 2,
  },
  {
    id: 'word_basic_030',
    word: 'curious',
    phonetic: '/ˈkjʊəriəs/',
    partOfSpeech: 'adj.',
    meaningZh: '好奇的',
    exampleEn: 'Children are curious about the world.',
    exampleZh: '孩子们对世界很好奇。',
    tags: 'basic,adjective',
    difficulty: 2,
  },
  {
    id: 'word_basic_031',
    word: 'decide',
    phonetic: '/dɪˈsaɪd/',
    partOfSpeech: 'v.',
    meaningZh: '决定',
    exampleEn: 'We decided to leave early.',
    exampleZh: '我们决定早点离开。',
    tags: 'basic,verb',
    difficulty: 1,
  },
  {
    id: 'word_basic_032',
    word: 'describe',
    phonetic: '/dɪˈskraɪb/',
    partOfSpeech: 'v.',
    meaningZh: '描述',
    exampleEn: 'Can you describe your school?',
    exampleZh: '你能描述一下你的学校吗？',
    tags: 'basic,verb',
    difficulty: 2,
  },
  {
    id: 'word_basic_033',
    word: 'develop',
    phonetic: '/dɪˈveləp/',
    partOfSpeech: 'v.',
    meaningZh: '发展；培养',
    exampleEn: 'Reading helps develop good habits.',
    exampleZh: '阅读有助于培养好习惯。',
    tags: 'basic,verb',
    difficulty: 3,
  },
  {
    id: 'word_basic_034',
    word: 'difference',
    phonetic: '/ˈdɪfrəns/',
    partOfSpeech: 'n.',
    meaningZh: '差异；不同',
    exampleEn: 'There is a big difference between them.',
    exampleZh: '它们之间有很大差异。',
    tags: 'basic,noun',
    difficulty: 2,
  },
  {
    id: 'word_basic_035',
    word: 'difficult',
    phonetic: '/ˈdɪfɪkəlt/',
    partOfSpeech: 'adj.',
    meaningZh: '困难的',
    exampleEn: 'This question is difficult.',
    exampleZh: '这个问题很难。',
    tags: 'basic,adjective',
    difficulty: 1,
  },
  {
    id: 'word_basic_036',
    word: 'discover',
    phonetic: '/dɪˈskʌvə/',
    partOfSpeech: 'v.',
    meaningZh: '发现',
    exampleEn: 'Scientists discover new facts every day.',
    exampleZh: '科学家每天都发现新事实。',
    tags: 'basic,science',
    difficulty: 2,
  },
  {
    id: 'word_basic_037',
    word: 'education',
    phonetic: '/ˌedʒuˈkeɪʃn/',
    partOfSpeech: 'n.',
    meaningZh: '教育',
    exampleEn: 'Education changes lives.',
    exampleZh: '教育改变人生。',
    tags: 'basic,school',
    difficulty: 2,
  },
  {
    id: 'word_basic_038',
    word: 'effort',
    phonetic: '/ˈefət/',
    partOfSpeech: 'n.',
    meaningZh: '努力',
    exampleEn: 'Success needs effort.',
    exampleZh: '成功需要努力。',
    tags: 'basic,noun',
    difficulty: 2,
  },
  {
    id: 'word_basic_039',
    word: 'encourage',
    phonetic: '/ɪnˈkʌrɪdʒ/',
    partOfSpeech: 'v.',
    meaningZh: '鼓励',
    exampleEn: 'My parents encourage me to try again.',
    exampleZh: '我的父母鼓励我再试一次。',
    tags: 'basic,verb',
    difficulty: 3,
  },
  {
    id: 'word_basic_040',
    word: 'energy',
    phonetic: '/ˈenədʒi/',
    partOfSpeech: 'n.',
    meaningZh: '能量；精力',
    exampleEn: 'Breakfast gives you energy.',
    exampleZh: '早餐给你能量。',
    tags: 'basic,health',
    difficulty: 2,
  },
  {
    id: 'word_basic_041',
    word: 'environment',
    phonetic: '/ɪnˈvaɪrənmənt/',
    partOfSpeech: 'n.',
    meaningZh: '环境',
    exampleEn: 'We should protect the environment.',
    exampleZh: '我们应该保护环境。',
    tags: 'basic,nature',
    difficulty: 3,
  },
  {
    id: 'word_basic_042',
    word: 'especially',
    phonetic: '/ɪˈspeʃəli/',
    partOfSpeech: 'adv.',
    meaningZh: '尤其；特别',
    exampleEn: 'I like fruit, especially apples.',
    exampleZh: '我喜欢水果，尤其是苹果。',
    tags: 'basic,adverb',
    difficulty: 2,
  },
  {
    id: 'word_basic_043',
    word: 'example',
    phonetic: '/ɪɡˈzɑːmpl/',
    partOfSpeech: 'n.',
    meaningZh: '例子；榜样',
    exampleEn: 'This sentence is an example.',
    exampleZh: '这个句子是一个例子。',
    tags: 'basic,noun',
    difficulty: 1,
  },
  {
    id: 'word_basic_044',
    word: 'experience',
    phonetic: '/ɪkˈspɪəriəns/',
    partOfSpeech: 'n./v.',
    meaningZh: '经历；经验',
    exampleEn: 'Travel gives people experience.',
    exampleZh: '旅行给人们带来经验。',
    tags: 'basic,noun',
    difficulty: 3,
  },
  {
    id: 'word_basic_045',
    word: 'explain',
    phonetic: '/ɪkˈspleɪn/',
    partOfSpeech: 'v.',
    meaningZh: '解释',
    exampleEn: 'Can you explain the rule?',
    exampleZh: '你能解释一下这个规则吗？',
    tags: 'basic,verb',
    difficulty: 2,
  },
  {
    id: 'word_basic_046',
    word: 'famous',
    phonetic: '/ˈfeɪməs/',
    partOfSpeech: 'adj.',
    meaningZh: '著名的',
    exampleEn: 'The city is famous for its food.',
    exampleZh: '这座城市以食物闻名。',
    tags: 'basic,adjective',
    difficulty: 1,
  },
  {
    id: 'word_basic_047',
    word: 'favorite',
    phonetic: '/ˈfeɪvərɪt/',
    partOfSpeech: 'adj./n.',
    meaningZh: '最喜欢的',
    exampleEn: 'English is my favorite subject.',
    exampleZh: '英语是我最喜欢的科目。',
    tags: 'basic,school',
    difficulty: 1,
  },
  {
    id: 'word_basic_048',
    word: 'festival',
    phonetic: '/ˈfestɪvl/',
    partOfSpeech: 'n.',
    meaningZh: '节日',
    exampleEn: 'The Spring Festival is important in China.',
    exampleZh: '春节在中国很重要。',
    tags: 'basic,culture',
    difficulty: 1,
  },
  {
    id: 'word_basic_049',
    word: 'future',
    phonetic: '/ˈfjuːtʃə/',
    partOfSpeech: 'n./adj.',
    meaningZh: '未来；将来的',
    exampleEn: 'Plan for your future.',
    exampleZh: '为你的未来做计划。',
    tags: 'basic,time',
    difficulty: 1,
  },
  {
    id: 'word_basic_050',
    word: 'general',
    phonetic: '/ˈdʒenrəl/',
    partOfSpeech: 'adj.',
    meaningZh: '一般的；总体的',
    exampleEn: 'This is a general rule.',
    exampleZh: '这是一个一般规则。',
    tags: 'basic,adjective',
    difficulty: 3,
  },
  {
    id: 'word_basic_051',
    word: 'habit',
    phonetic: '/ˈhæbɪt/',
    partOfSpeech: 'n.',
    meaningZh: '习惯',
    exampleEn: 'Reading every day is a good habit.',
    exampleZh: '每天阅读是一个好习惯。',
    tags: 'basic,life',
    difficulty: 1,
  },
  {
    id: 'word_basic_052',
    word: 'healthy',
    phonetic: '/ˈhelθi/',
    partOfSpeech: 'adj.',
    meaningZh: '健康的',
    exampleEn: 'A healthy diet is important.',
    exampleZh: '健康饮食很重要。',
    tags: 'basic,health',
    difficulty: 1,
  },
  {
    id: 'word_basic_053',
    word: 'history',
    phonetic: '/ˈhɪstri/',
    partOfSpeech: 'n.',
    meaningZh: '历史',
    exampleEn: 'We study history at school.',
    exampleZh: '我们在学校学习历史。',
    tags: 'basic,school',
    difficulty: 1,
  },
  {
    id: 'word_basic_054',
    word: 'improve',
    phonetic: '/ɪmˈpruːv/',
    partOfSpeech: 'v.',
    meaningZh: '提高；改善',
    exampleEn: 'Practice can improve your speaking.',
    exampleZh: '练习可以提高你的口语。',
    tags: 'basic,study',
    difficulty: 2,
  },
  {
    id: 'word_basic_055',
    word: 'include',
    phonetic: '/ɪnˈkluːd/',
    partOfSpeech: 'v.',
    meaningZh: '包括',
    exampleEn: 'The price includes lunch.',
    exampleZh: '价格包括午餐。',
    tags: 'basic,verb',
    difficulty: 2,
  },
  {
    id: 'word_basic_056',
    word: 'increase',
    phonetic: '/ɪnˈkriːs/',
    partOfSpeech: 'v./n.',
    meaningZh: '增加',
    exampleEn: 'The number of students increased.',
    exampleZh: '学生人数增加了。',
    tags: 'basic,verb',
    difficulty: 3,
  },
  {
    id: 'word_basic_057',
    word: 'interest',
    phonetic: '/ˈɪntrəst/',
    partOfSpeech: 'n./v.',
    meaningZh: '兴趣；使感兴趣',
    exampleEn: 'Music is one of my interests.',
    exampleZh: '音乐是我的兴趣之一。',
    tags: 'basic,life',
    difficulty: 1,
  },
  {
    id: 'word_basic_058',
    word: 'introduce',
    phonetic: '/ˌɪntrəˈdjuːs/',
    partOfSpeech: 'v.',
    meaningZh: '介绍',
    exampleEn: 'Let me introduce my friend.',
    exampleZh: '让我介绍我的朋友。',
    tags: 'basic,verb',
    difficulty: 2,
  },
  {
    id: 'word_basic_059',
    word: 'knowledge',
    phonetic: '/ˈnɒlɪdʒ/',
    partOfSpeech: 'n.',
    meaningZh: '知识',
    exampleEn: 'Books give us knowledge.',
    exampleZh: '书籍给我们知识。',
    tags: 'basic,school',
    difficulty: 2,
  },
  {
    id: 'word_basic_060',
    word: 'language',
    phonetic: '/ˈlæŋɡwɪdʒ/',
    partOfSpeech: 'n.',
    meaningZh: '语言',
    exampleEn: 'English is a useful language.',
    exampleZh: '英语是一门有用的语言。',
    tags: 'basic,school',
    difficulty: 1,
  },
  {
    id: 'word_basic_061',
    word: 'local',
    phonetic: '/ˈləʊkl/',
    partOfSpeech: 'adj.',
    meaningZh: '当地的；本地的',
    exampleEn: 'We visited a local museum.',
    exampleZh: '我们参观了当地的一家博物馆。',
    tags: 'basic,place',
    difficulty: 2,
  },
  {
    id: 'word_basic_062',
    word: 'memory',
    phonetic: '/ˈmeməri/',
    partOfSpeech: 'n.',
    meaningZh: '记忆；记忆力',
    exampleEn: 'Sleep is good for memory.',
    exampleZh: '睡眠对记忆有好处。',
    tags: 'basic,study',
    difficulty: 2,
  },
  {
    id: 'word_basic_063',
    word: 'message',
    phonetic: '/ˈmesɪdʒ/',
    partOfSpeech: 'n.',
    meaningZh: '消息；信息',
    exampleEn: 'I received your message.',
    exampleZh: '我收到了你的消息。',
    tags: 'basic,communication',
    difficulty: 1,
  },
  {
    id: 'word_basic_064',
    word: 'method',
    phonetic: '/ˈmeθəd/',
    partOfSpeech: 'n.',
    meaningZh: '方法',
    exampleEn: 'This method works well.',
    exampleZh: '这个方法很有效。',
    tags: 'basic,study',
    difficulty: 2,
  },
  {
    id: 'word_basic_065',
    word: 'natural',
    phonetic: '/ˈnætʃrəl/',
    partOfSpeech: 'adj.',
    meaningZh: '自然的',
    exampleEn: 'The lake has natural beauty.',
    exampleZh: '这个湖有自然之美。',
    tags: 'basic,nature',
    difficulty: 2,
  },
  {
    id: 'word_basic_066',
    word: 'necessary',
    phonetic: '/ˈnesəsəri/',
    partOfSpeech: 'adj.',
    meaningZh: '必要的',
    exampleEn: 'It is necessary to review often.',
    exampleZh: '经常复习是必要的。',
    tags: 'basic,adjective',
    difficulty: 3,
  },
  {
    id: 'word_basic_067',
    word: 'notice',
    phonetic: '/ˈnəʊtɪs/',
    partOfSpeech: 'n./v.',
    meaningZh: '通知；注意到',
    exampleEn: 'Did you notice the sign?',
    exampleZh: '你注意到那个标志了吗？',
    tags: 'basic,communication',
    difficulty: 2,
  },
  {
    id: 'word_basic_068',
    word: 'opinion',
    phonetic: '/əˈpɪnjən/',
    partOfSpeech: 'n.',
    meaningZh: '观点；意见',
    exampleEn: 'Everyone can share an opinion.',
    exampleZh: '每个人都可以分享观点。',
    tags: 'basic,communication',
    difficulty: 2,
  },
  {
    id: 'word_basic_069',
    word: 'order',
    phonetic: '/ˈɔːdə/',
    partOfSpeech: 'n./v.',
    meaningZh: '顺序；命令；点餐',
    exampleEn: 'Put the words in the right order.',
    exampleZh: '把单词按正确顺序排列。',
    tags: 'basic,noun',
    difficulty: 2,
  },
  {
    id: 'word_basic_070',
    word: 'ordinary',
    phonetic: '/ˈɔːdnri/',
    partOfSpeech: 'adj.',
    meaningZh: '普通的；平常的',
    exampleEn: 'It was an ordinary day.',
    exampleZh: '那是平常的一天。',
    tags: 'basic,adjective',
    difficulty: 2,
  },
  {
    id: 'word_basic_071',
    word: 'patient',
    phonetic: '/ˈpeɪʃnt/',
    partOfSpeech: 'adj./n.',
    meaningZh: '有耐心的；病人',
    exampleEn: 'A good teacher is patient.',
    exampleZh: '好老师有耐心。',
    tags: 'basic,adjective',
    difficulty: 2,
  },
  {
    id: 'word_basic_072',
    word: 'perfect',
    phonetic: '/ˈpɜːfɪkt/',
    partOfSpeech: 'adj.',
    meaningZh: '完美的',
    exampleEn: 'Practice does not need to be perfect.',
    exampleZh: '练习不需要完美。',
    tags: 'basic,adjective',
    difficulty: 2,
  },
  {
    id: 'word_basic_073',
    word: 'popular',
    phonetic: '/ˈpɒpjələ/',
    partOfSpeech: 'adj.',
    meaningZh: '受欢迎的；流行的',
    exampleEn: 'Basketball is popular here.',
    exampleZh: '篮球在这里很受欢迎。',
    tags: 'basic,life',
    difficulty: 1,
  },
  {
    id: 'word_basic_074',
    word: 'possible',
    phonetic: '/ˈpɒsəbl/',
    partOfSpeech: 'adj.',
    meaningZh: '可能的',
    exampleEn: 'Everything is possible with effort.',
    exampleZh: '努力后一切皆有可能。',
    tags: 'basic,adjective',
    difficulty: 1,
  },
  {
    id: 'word_basic_075',
    word: 'practice',
    phonetic: '/ˈpræktɪs/',
    partOfSpeech: 'n./v.',
    meaningZh: '练习；实践',
    exampleEn: 'Daily practice improves English.',
    exampleZh: '每天练习可以提高英语。',
    tags: 'basic,study',
    difficulty: 1,
  },
  {
    id: 'word_basic_076',
    word: 'prepare',
    phonetic: '/prɪˈpeə/',
    partOfSpeech: 'v.',
    meaningZh: '准备',
    exampleEn: 'We need to prepare for the test.',
    exampleZh: '我们需要为考试做准备。',
    tags: 'basic,study',
    difficulty: 2,
  },
  {
    id: 'word_basic_077',
    word: 'probably',
    phonetic: '/ˈprɒbəbli/',
    partOfSpeech: 'adv.',
    meaningZh: '大概；很可能',
    exampleEn: 'It will probably rain tomorrow.',
    exampleZh: '明天很可能会下雨。',
    tags: 'basic,adverb',
    difficulty: 3,
  },
  {
    id: 'word_basic_078',
    word: 'progress',
    phonetic: '/ˈprəʊɡres/',
    partOfSpeech: 'n./v.',
    meaningZh: '进步；进展',
    exampleEn: 'You made great progress this month.',
    exampleZh: '你这个月取得了很大进步。',
    tags: 'basic,study',
    difficulty: 2,
  },
  {
    id: 'word_basic_079',
    word: 'protect',
    phonetic: '/prəˈtekt/',
    partOfSpeech: 'v.',
    meaningZh: '保护',
    exampleEn: 'We should protect our eyes.',
    exampleZh: '我们应该保护眼睛。',
    tags: 'basic,health',
    difficulty: 2,
  },
  {
    id: 'word_basic_080',
    word: 'provide',
    phonetic: '/prəˈvaɪd/',
    partOfSpeech: 'v.',
    meaningZh: '提供',
    exampleEn: 'The school provides lunch.',
    exampleZh: '学校提供午餐。',
    tags: 'basic,verb',
    difficulty: 3,
  },
  {
    id: 'word_basic_081',
    word: 'purpose',
    phonetic: '/ˈpɜːpəs/',
    partOfSpeech: 'n.',
    meaningZh: '目的；用途',
    exampleEn: 'What is the purpose of this activity?',
    exampleZh: '这个活动的目的是什么？',
    tags: 'basic,noun',
    difficulty: 3,
  },
  {
    id: 'word_basic_082',
    word: 'realize',
    phonetic: '/ˈriːəlaɪz/',
    partOfSpeech: 'v.',
    meaningZh: '意识到；实现',
    exampleEn: 'I realized my mistake.',
    exampleZh: '我意识到了自己的错误。',
    tags: 'basic,verb',
    difficulty: 2,
  },
  {
    id: 'word_basic_083',
    word: 'reason',
    phonetic: '/ˈriːzn/',
    partOfSpeech: 'n.',
    meaningZh: '原因；理由',
    exampleEn: 'Tell me the reason.',
    exampleZh: '告诉我原因。',
    tags: 'basic,noun',
    difficulty: 1,
  },
  {
    id: 'word_basic_084',
    word: 'receive',
    phonetic: '/rɪˈsiːv/',
    partOfSpeech: 'v.',
    meaningZh: '收到；接收',
    exampleEn: 'I received a letter yesterday.',
    exampleZh: '我昨天收到了一封信。',
    tags: 'basic,verb',
    difficulty: 2,
  },
  {
    id: 'word_basic_085',
    word: 'record',
    phonetic: '/ˈrekɔːd/',
    partOfSpeech: 'n./v.',
    meaningZh: '记录',
    exampleEn: 'Keep a record of new words.',
    exampleZh: '记录新单词。',
    tags: 'basic,study',
    difficulty: 2,
  },
  {
    id: 'word_basic_086',
    word: 'reduce',
    phonetic: '/rɪˈdjuːs/',
    partOfSpeech: 'v.',
    meaningZh: '减少',
    exampleEn: 'We should reduce waste.',
    exampleZh: '我们应该减少浪费。',
    tags: 'basic,nature',
    difficulty: 3,
  },
  {
    id: 'word_basic_087',
    word: 'remember',
    phonetic: '/rɪˈmembə/',
    partOfSpeech: 'v.',
    meaningZh: '记得；记住',
    exampleEn: 'Remember to review the words.',
    exampleZh: '记得复习单词。',
    tags: 'basic,study',
    difficulty: 1,
  },
  {
    id: 'word_basic_088',
    word: 'repeat',
    phonetic: '/rɪˈpiːt/',
    partOfSpeech: 'v.',
    meaningZh: '重复',
    exampleEn: 'Please repeat the sentence.',
    exampleZh: '请重复这个句子。',
    tags: 'basic,study',
    difficulty: 1,
  },
  {
    id: 'word_basic_089',
    word: 'report',
    phonetic: '/rɪˈpɔːt/',
    partOfSpeech: 'n./v.',
    meaningZh: '报告；报道',
    exampleEn: 'She wrote a report about the trip.',
    exampleZh: '她写了一篇关于旅行的报告。',
    tags: 'basic,school',
    difficulty: 2,
  },
  {
    id: 'word_basic_090',
    word: 'require',
    phonetic: '/rɪˈkwaɪə/',
    partOfSpeech: 'v.',
    meaningZh: '需要；要求',
    exampleEn: 'This job requires patience.',
    exampleZh: '这份工作需要耐心。',
    tags: 'basic,verb',
    difficulty: 3,
  },
  {
    id: 'word_basic_091',
    word: 'result',
    phonetic: '/rɪˈzʌlt/',
    partOfSpeech: 'n.',
    meaningZh: '结果',
    exampleEn: 'The result was better than expected.',
    exampleZh: '结果比预期更好。',
    tags: 'basic,noun',
    difficulty: 1,
  },
  {
    id: 'word_basic_092',
    word: 'review',
    phonetic: '/rɪˈvjuː/',
    partOfSpeech: 'n./v.',
    meaningZh: '复习；回顾',
    exampleEn: 'Review the words before class.',
    exampleZh: '上课前复习这些单词。',
    tags: 'basic,study',
    difficulty: 1,
  },
  {
    id: 'word_basic_093',
    word: 'science',
    phonetic: '/ˈsaɪəns/',
    partOfSpeech: 'n.',
    meaningZh: '科学',
    exampleEn: 'Science helps us understand nature.',
    exampleZh: '科学帮助我们理解自然。',
    tags: 'basic,school',
    difficulty: 1,
  },
  {
    id: 'word_basic_094',
    word: 'serious',
    phonetic: '/ˈsɪəriəs/',
    partOfSpeech: 'adj.',
    meaningZh: '严肃的；严重的',
    exampleEn: 'This is a serious problem.',
    exampleZh: '这是一个严重的问题。',
    tags: 'basic,adjective',
    difficulty: 2,
  },
  {
    id: 'word_basic_095',
    word: 'similar',
    phonetic: '/ˈsɪmələ/',
    partOfSpeech: 'adj.',
    meaningZh: '相似的',
    exampleEn: 'The two words are similar.',
    exampleZh: '这两个单词很相似。',
    tags: 'basic,adjective',
    difficulty: 2,
  },
  {
    id: 'word_basic_096',
    word: 'simple',
    phonetic: '/ˈsɪmpl/',
    partOfSpeech: 'adj.',
    meaningZh: '简单的',
    exampleEn: 'Start with simple words.',
    exampleZh: '从简单单词开始。',
    tags: 'basic,adjective',
    difficulty: 1,
  },
  {
    id: 'word_basic_097',
    word: 'situation',
    phonetic: '/ˌsɪtʃuˈeɪʃn/',
    partOfSpeech: 'n.',
    meaningZh: '情况；形势',
    exampleEn: 'We need to understand the situation.',
    exampleZh: '我们需要了解情况。',
    tags: 'basic,noun',
    difficulty: 3,
  },
  {
    id: 'word_basic_098',
    word: 'solution',
    phonetic: '/səˈluːʃn/',
    partOfSpeech: 'n.',
    meaningZh: '解决办法',
    exampleEn: 'We found a solution to the problem.',
    exampleZh: '我们找到了问题的解决办法。',
    tags: 'basic,study',
    difficulty: 3,
  },
  {
    id: 'word_basic_099',
    word: 'special',
    phonetic: '/ˈspeʃl/',
    partOfSpeech: 'adj.',
    meaningZh: '特别的；特殊的',
    exampleEn: 'Today is a special day.',
    exampleZh: '今天是特别的一天。',
    tags: 'basic,adjective',
    difficulty: 1,
  },
  {
    id: 'word_basic_100',
    word: 'success',
    phonetic: '/səkˈses/',
    partOfSpeech: 'n.',
    meaningZh: '成功',
    exampleEn: 'Hard work leads to success.',
    exampleZh: '努力带来成功。',
    tags: 'basic,study',
    difficulty: 1,
  },
]
